trigger:
- main

pool:
  name: Default  # Agente local configurado

variables:
  ACR_NAME: 'mrluxus'
  IMAGE_NAME: 'front-erp'
  RESOURCE_GROUP: 'erp-final'
  WEBAPP_NAME: 'frontErp'

stages:
# -------- STAGE BUILD --------
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildJob
    displayName: 'Build Docker Image'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: 'acr-erp'  # Nombre de tu conexión al ACR

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest .
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
      displayName: 'Build and Push Image'

# -------- STAGE DEPLOY --------
- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Frontend'
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Docker Image to App Service'
      inputs:
        azureSubscription: 'ConexionAzure'  # Tu conexión a Azure
        appName: $(WEBAPP_NAME)
        resourceGroupName: $(RESOURCE_GROUP)
        containers: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest'
