trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'mrluxus'
  IMAGE_NAME: 'front-erp'
  RESOURCE_GROUP: 'erp-final'
  WEBAPP_NAME: 'frontErp'

stages:
# -------- STAGE BUILD --------
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildJob
    displayName: 'Build Docker Image'
    steps:
    - checkout: self

    - task: DockerInstaller@0
      displayName: 'Instalar Docker'

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: 'acr-erp'   # <- Service Connection tipo Docker Registry hacia tu ACR

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest .
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
      displayName: 'Build and Push Image'

# -------- STAGE DEPLOY --------
- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Frontend'
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Docker Image to App Service'
      inputs:
        azureSubscription: 'back erp'    # <- Esta es la conexión de tipo Azure Resource Manager
        appName: $(WEBAPP_NAME)
        containers: $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
