name: Build and deploy React+TypeScript app to Azure Web App - frontErp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' 

      - name: Install dependencies
        run: npm ci

      - name: Build the React app 
        run: CI=false npm run build

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: Create .deployment file with startup command
        run: |
          echo "[config]" > .deployment
          echo "command = npm install && npm start" >> .deployment

      - name: Zip full project for deployment (excluding node_modules and .git)
        run: zip -r release.zip . -x "node_modules/*" ".git/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-full-project
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-full-project

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1FEE206C695B45708520DB2C58DA947A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_655B310463434D25B8E2A827D1A75F87 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7FDC33D9A0B24143A14B33066609E820 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontErp'      
          slot-name: 'Production'
          package: '.'  # carpeta raíz con package.json y .deployment
