jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: CI=false npm run build

      - name: Copy package.json and lockfile to build folder
        run: |
          cp package.json build/
          cp package-lock.json build/

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: Zip build folder
        run: zip -r build.zip build

      - name: Upload zipped build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build.zip
