name: Build and deploy React+TypeScript app to Azure Web App - frontErp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'   # Node 18 es estable y compatible con React y TS

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: npm run build

      - name: Run tests
        run: npm test -- --coverage --watchAll=false

      - name: Zip build output for deployment
        run: zip -r release.zip build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontErp'       # Nombre de tu Azure Web App
          slot-name: 'Production'    # O 'staging' si tienes slots
          package: './build'         # Carpeta build generada por React
